### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by sebfie** [rpush/rpush#186]
Hello, when I try to create my app Rpush::Apns::App.new , read the sandbox.pem using File.read return me this error : 

```
ArgumentError: invalid byte sequence in UTF-8
from /Users/sebfie/.rvm/gems/ruby-2.1.5@paycar-api/gems/activesupport-4.2.1/lib/active_support/core_ext/object/blank.rb:117:in `==='
```

Any idea?

**Comment by sebfie** [comment]
ok, it came from my last_name "sébastien"

**Comment by Papipo** [comment]
I am having the same problem. Does this mean that I can't use my proper name?

**Comment by seccomiro** [comment]
Did anybody manage to solve this?

**Comment by aried3r** [comment]
@seccomiro, do you have code that reproduces this error with the latest Rpush version?

**Comment by seccomiro** [comment]
Hey @aried3r.
I don't have a piece of code, because the problem wasn't directly related to it.
After some hours of headache I figured out that the problem was, as @sebfie pointed, the accented words (Brazilian, in my case) **inside my .pem certificate** (at the _friendlyName_ attribute).

    -----more above-----
    -----END CERTIFICATE-----
    Bag Attributes
    friendlyName: a_name_with_á_or_ó_or_é_or_etc
    localKeyID: XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX
    Key Attributes: <No Attributes>
    -----BEGIN PRIVATE KEY-----
    -----more below-----

Regenerating the certificate on the Keychain Access solved this for me.
