### ISSUE TITLE
APNS Notifications not delivered after reconnect due to error in apns/notification.rb

### ISSUE THREAD

**Issue by gdeglin** [rpush/rpush#206]
apns/notification.rb sets the notification expiry incorrectly. As documented here https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html, this value is supposed to be a epoch date. For instance: `(Time.now+1.day).to_i`

Instead, rpush defaults to `1.day.to_i`.

This effectively causes the expiry to be equal to 0, and Apple's servers will not store the notification for future delivery if the device is presently offline.

**Comment by gdeglin** [comment]
That this problem may not have been discovered earlier because Apple's servers seemed to retry delivery despite this bug until recently.

**Comment by amaierhofer** [comment]
I can confirm this APNS issue. I pushed to both ios and android devices in flight mode. After returning from flight mode, android received push, ios did not.

**Comment by oliveriobw** [comment]
Any progress on this? This seems to be still an issue.

**Comment by jussihuotari** [comment]
I see this issue as well. 

The Apnsp8 actually explicitly sets the value to zero despite the value specified in the notification:

https://github.com/rpush/rpush/blob/5839fb9aa21c93b567d69f9766f57581333028df/lib/rpush/daemon/apnsp8/delivery.rb#L138

vs what's stored in the notifications:

```
> Rpush::Apns::Notification.last(5).pluck(:expiry)
=> [86400, 86400, 86400, 86400, 86400]
```

There's a workaround (for Apns2 and Apnsp8) as you can set headers case-by-case. For example, for Apnsp8:

```
n = Rpush::Apns::Notification.new
n.app = Rpush::Apnsp8::App.find_by_name("ios_app")
n.device_token = "..." # hex string
n.alert = "hi mom!"
n.data = { foo: :bar, , 'headers': {'apns-expiration': (Time.now+1.hour).getutc.to_i}}
n.save!
```

Actually, one could argue this issue is "only" missing documentation instead of a bug.. 🤔

btw the issue author's link to Apple's docs seems to be dead. Here's a more recent version: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
