### ISSUE TITLE
Using Redis, do notifications and feedback get deleted automatically?

### ISSUE THREAD

**Issue by jim0020** [rpush/rpush#212]
I'm using Redis as my rpush datastore, and I see the number of items in the cache continually climbing to the point where we have to restart redis.  Does rpush delete/destroy notifications and feedback records  from Redis when rpush is done with them, or do I have to do that myself?  If I have to delete them, what's the recommended way?  Are you supposed to delete the records with the reflection api?

**Comment by squarism** [comment]
I'm wondering the same thing using an activerecord store.  At this point, I'm going to manage the data myself with a cron (or in-process equivalent) job to query for `delivered is true` etc.  Should be fun.  I don't know what the feedback table actually buys you.  A log?

**Comment by ileitch** [comment]
Do not delete using the reflection API. I'd suggest some scheduled job, i.e cron to delete anything older than 24 hours

**Comment by squarism** [comment]
I see, by _the reflection API_, you mean don't do it in the callbacks in the generated rpush.rb config.

**Comment by ileitch** [comment]
No, the [feedback service[(https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW3) is separate. You should monitor it, and stop sending PNs to devices that appear in it.

**Comment by squarism** [comment]
It seems like the reflection API would be very convenient to monitor the feedback service and stop sending PNs.  Why is this a bad idea?  Database load?  Unintended use case?  Just wondering before I get into a gotcha.  :smile: 

Otherwise, I'd have to push feedback somewhere and work those jobs as cleanup tasks I guess?  Design another system myself?

**Comment by ileitch** [comment]
The reflection API is a good place to monitor the feedback service and disable tokens as appropriate for your system. The reflection API is not a good place for cleanup of old delivered notification records.

**Comment by jim0020** [comment]
The recommended way of deleting old notification and feedback records really needs to be documented in the README.  I was within an hour of deploying to production using the reflection api to delete completed notification and feedback records.

So you are saying I should be using a cron job to delete notification and feedback records older than 1 day?

**Comment by ileitch** [comment]
Yes. But only delete the feedback records once you have disabled the associated token.

**Comment by jim0020** [comment]
So...just making sure.

Use the reflection api to update or disable tokens.
And have a cron job delete all notification and feedback records older than 24 hours.

**Comment by daniel-nelson** [comment]
Is this documented anywhere? I missed the fact that push notification records are stored indefinitely until we started throwing Redis memory errors this morning because after 8 months of push notifications, we'd used up all our memory. If it isn't documented, I'd be happy to make a pull request to the readme (or perhaps simply update the Redis Wiki with a possible solution).

**Comment by aried3r** [comment]
Hey @daniel-nelson! I don't think this has been documented anywhere so far. I'm not sure where I stand between README and Wiki. The README is always versioned the same as current codebase whereas the Wiki is also versioned, but can be "out-of-sync" with the releases.

But since the Wiki can be edited by the community, I find this a big plus. Could you maybe make a PR to the README and if you wish, also leave that info in the Wiki? I think many people would appreciate that and not run into memory errors.

**Comment by vzamanillo** [comment]
@jim0020 , @daniel-nelson, I know this issue is quite old, but, could you please provide an example on how to do this?

- Use the reflection api to update or disable tokens.

- Have a cron job delete all notification and feedback records older than 24 hours.

I suppose I need a task (rake) to connect to redis and do the documented job

```
    redis = Redis.new(host: "localhost", port: 6380, db: 1)
    redis.keys('rpush:notifications:*').each do |key|
      next unless redis.ttl(key) == -1
      next unless redis.type(key) == 'hash'
      next if redis.hget(key, 'delivered').nil?
      redis.expire(key, 24.hours.to_i)
    end
```
Thank you very much!
