### ISSUE TITLE
APNS app is never found with Redis

### ISSUE THREAD

**Issue by joemasilotti** [rpush/rpush#295]
`Rpush::Apns::App#find` always raises `Modis::RecordNotFound`.

``` ruby
app = Rpush::Apns::App.new
app.name = 'ios_app'
app.certificate = File.read('path/to/valid/pem')
app.environment = "production"
app.save!

Rpush::Apns::App.find('ios_app')
# Modis::RecordNotFound: Couldn't find Rpush::Client::Redis::Apns::App with id=ios_app
```

Here is `/config/initializers/rpush.rb`, just in case:

``` ruby
Rpush.configure do |config|
  config.client = :redis

  uri = URI.parse(ENV["REDIS_URL"])
  config.redis_options = { host: uri.host, port: uri.port, password: uri.password }

  config.push_poll = 2

  config.batch_size = 100

  config.log_level = (defined?(Rails) && Rails.logger) ? Rails.logger.level : ::Logger::Severity::INFO

  config.apns.feedback_receiver.enabled = true
end

Rpush.reflect do |on|
  on.apns_feedback do |feedback|
    User.delete_invalid_ios_push_token(feedback.device_token)
  end

  on.notification_failed do |notification|
    if notification.error_code == 8 # invalid token
      User.delete_invalid_ios_push_token(notification.device_token)
    end
  end
end
```

I'm using `rpush` 2.7.0 and `redis` 3.1.0. Am I missing something or is there a bug in `modis`?

**Comment by joemasilotti** [comment]
As a workaround, one can do the following:

`Rpush::Apns::App.where(name: 'ios_app').first`

Which makes me think this is an issue in the [`Modis`](https://github.com/ileitch/modis) dependency, but I'm not 100% sure.

**Comment by aried3r** [comment]
I am not using Rpush with Redis, but could it be related to what is being discussed here: https://github.com/rpush/rpush/pull/166?

**Comment by Tonkpils** [comment]
> Rpush::Apns::App.find('ios_app')

The issue here is you're attempting to use `find` to fetch a record by an attribute. This would blow up with active record as well (e.g `User.find('leo')`). If you knew the `id` of the record stored by modis in redis then you'd be able to find the record using that id. This is what the implementation of `where` does. It finds the ids for the records with the given attribute and value then fetches those records. 

The workaround you found is currently the only way to fetch records with Modis by attribute.

**Comment by aried3r** [comment]
Closing, since this doesn't seem to be an error with Rpush.
