### ISSUE TITLE
Error in Gcm v2.7.0 ArgumentError

### ISSUE THREAD

**Issue by vtm9** [rpush/rpush#358]
Error in version 2.7.0 when I try to push to Fcm.
`[2017-05-30 13:43:50] [android] Starting 1 dispatcher... [2017-05-30 13:43:50] [ERROR] [android] Exception raised during startup. Notifications will not be delivered for this app.
[2017-05-30 13:43:50] [ERROR] ArgumentError, wrong number of arguments (given 1, expected 0)
/home/vtm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-http-persistent3.0.0/lib/net/http/persistent.rb:505:in initialize'
/home/vtm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rpush2.7.0/lib/rpush/daemon/dispatcher/http.rb:8:in new'`

When I use master branch it works Good. 

Difference in this classes
2.7.0: `Net::HTTP::Persistent.new('rpush') `

master: `Net::HTTP::Persistent.new(name: 'rpush') `

Maybe tag new version of gem? 
Thanks  all!

**Comment by vtm9** [comment]
maybe cherry-pick this commit 709ce4d2 to v.2.7.0

**Comment by ctmaloney** [comment]
Having this issue also

**Comment by aried3r** [comment]
This has been fixed in the `master` branch. Since the original author of this gem does no longer actively maintain it, a few contributors have been chosen which sometimes commit fixes.

So, sadly we cannot simply back port it. Your other option besides using the `master` branch (which includes other bugfixes as well), – if no other dependency relies on ≥3.0 – is to lock `net-http-persistent` to `< 3` in your Gemfile.

**Comment by vtm9** [comment]
@aried3r Ok. Thank you!
