### ISSUE TITLE
Apns2 - 400/MissingTopic

### ISSUE THREAD

**Issue by homburg** [rpush/rpush#363]
Hi

After creating an Rpush Apns2 app we are getting `400/MissingTopic` errors for notifications for a production certificate.

Anyone else experiencing this?

**Comment by Nattfodd** [comment]
When you create a new Rpush::Notification, set ` { aps: { headers: { 'apns-topic': 'your.bundle.identifier.com' } } `

**Comment by homburg** [comment]
Thank you for your reply.

I was looking at this gist: https://gist.github.com/naumov/b7a0a320336c3d396ce5cffcbcf42c1e

with:

```ruby
notification.data = { 'headers' => { 'apns-topic' => 'com.example.bundle.id' }, ...}
```

Where does the `aps` key fit?

**Comment by homburg** [comment]
After adding the header field as above, I'm receiving `400/BadDeviceToken` instead.

Could this be caused by the wrong bundle id in `apns-topic`?

**Comment by Nattfodd** [comment]
No, if wrong apns-topic provided, there is "400/DeviceTokenNotForTopic" error. BadDeviceToken means device token does not exist.

**Comment by aried3r** [comment]
Hey @homburg, were you able to successfully resolve this issue?

**Comment by homburg** [comment]
Sorry, do not remember the resolution. Bad form on my part.

**Comment by Babbz75** [comment]
Hey guys,
I'm using rpush for ios notifications and i'm getting this error after switching to Apns2:
`Notification 472 failed, 400/MissingTopic`
when you to a topic needs to be added, can I do that in the console something like
`Rpush::Apns2::App.first.topic = 'mybundleid'`

**Comment by aried3r** [comment]
Hey there, sadly I don't use APNS at all so I can't really help you. But if anyone wants to chime in or submit a PR I'd be happy to merge and release that. Given that I don't use APNS and thus have little knowledge about it, I would need somebody else to review it.

I have a few questions though, is the `apns-topic` a mandatory field? Is there documentation for that? If it is mandatory, then I think Rpush should already validate that instead of people having to rely on the feedback service or response of Apple's push servers.

**Comment by Babbz75** [comment]
@aried3r I believe it's only mandatory in Apns2 and I'm not sure about the documentation part.

For anyone who runs into this problem in the future you just need to add a similar merge into the data section when sending push notifications:
`@data.merge!(headers: { 'apns-topic': ENV['APNS_BUNDLE_ID'] }) if ENV.key?('APNS_BUNDLE_ID')`

**Comment by sungsong88** [comment]
@Babbz75 Omg. Thank you so much! just adding that to my data for my Apns2 solved my issue! No more MissingTopic!!
