### ISSUE TITLE
Why did you add a mutable_content column in the database?

### ISSUE THREAD

**Issue by philipgiuliani** [rpush/rpush#381]
It seems to me that the column `mutable_content` its not used. When i set `notification.mutable_content = true` it will just add `{ "__rpush_mutable_content__":true }` in the data but the column value will remain to 0.

It currently works the same as `content_available` does.

@tdtran

**Comment by tdtran** [comment]
I did it only to be consistent with how rpush deals with other attributes. It seems they are making a transition from one db column per attr to storing them all in json

**Comment by philipgiuliani** [comment]
Ok, I get it! But than I would remove the setter (otherwise the column is never used) 
https://github.com/rpush/rpush/blob/0546b5e25218763aa1edd012fa52a281d5648da8/lib/rpush/client/active_model/apns/notification.rb#L36

And change https://github.com/rpush/rpush/blob/0546b5e25218763aa1edd012fa52a281d5648da8/lib/rpush/client/active_model/apns/notification.rb#L60 to be:
```
json['aps']['mutable-content'] = 1 if mutable_content
```

----------

Or else: Remove the unused column...

@aried3r What do you think?

**Comment by aried3r** [comment]
Phew, I haven't really used APNS since we use FCM for both iOS and Android, but I'm open for PRs if there is a bug or useless behavior.

As for the move away from DB columns, we haven't really discussed moving away from DB models to using JSON (probably combined with models that then do the verification), but it would be more flexible I guess, since now we have to add functionality and release a new version of Rpush whenever FCM or APNS gets new payloads.

**Comment by philipgiuliani** [comment]
Ok thank you :)
