### ISSUE TITLE
Validation error (apn_key is too long) when reading the APNs .p8 key

### ISSUE THREAD

**Issue by sonxurxo** [rpush/rpush#442]
Hi all

I'm trying to send a notification to an iOS device using the .p8 key. I followed the instructions in the README, reading the key directly from the .p8 file, and a SQL error raises telling that the `apn_key` is too long (257 VS the 255 default length for the Varchar column generated in the migration, at least in MySQL).

I think those 2 extra chars are used for the 2 new-lines in the key file.

If this is an actual issue, I'm up for submitting a pull request if you like.

-----

**EDIT**: fixed a typo in the needed length, "277" -> "257"

**Comment by mariannegru** [comment]
I think we need to add a migration to change the column type to :text

**Comment by sonxurxo** [comment]
I fixed this in my project just extending the limit to 257 chars to avoid changing the data type. But maybe this can lead to issues in the future.

**Comment by aried3r** [comment]
Ok, since I don't use APNS I had to read up on that a bit, please correct me if I'm wrong.

So a `.p8` file is a PEM-encoded, unencrypted PKCS#8 file. If I understood [RFC5208](https://tools.ietf.org/html/rfc5208) correctly, it makes no assumptions on key length, especially considering padding I guess the length can vary a bit.

Should we even set any kind of limit?

**Comment by sonxurxo** [comment]
I think you're right, I didn't even read that RFC. So I guess changing column type to :text should work.

**Comment by BagpipesJohnson** [comment]
I am running into this issue as well. I think the migration to change the column type to :text should do it

**Comment by sonxurxo** [comment]
Just created PR #455 for this.

**Comment by zedtux** [comment]
I'm facing this issue. Any news ?

**Comment by sonxurxo** [comment]
@zedtux If you need to get this running, maybe you can just change the column type adding a migration like the following to your application:

`change_column :rpush_apps, :apn_key, :text, null: true `

**Comment by zedtux** [comment]
I did that, thank you @sonxurxo, but this issue is quite embarrassing and should be solved as soon as possible from my point of view.

**Comment by aried3r** [comment]
This has been resolved by #455 (thanks @sonxurxo!). However since we're currently facing some failing tests regarding Rails 5.2 in the master branch (that being said, we use Rails 5.2.1 with the latest Rpush at work and are not facing any problems), I cannot in good faith make a new release with this right now.

Sadly I cannot look into this right now, sorry :\. But I think I won't be the only one being very happy if someone could look into this.

The only thing I can offer right now is pointing your gem files towards `master` or copying the migration yourself from the PR mentioned above. Hope to see this being resolved soon!

**Comment by mariannegru** [comment]
Thank you @sonxurxo
