### ISSUE TITLE
FCM supported?

### ISSUE THREAD

**Issue by AkshayGoyal022** [rpush/rpush#466]
I am initialising a project which uses push notifications. I went through the documentation and it's not clear how to use FCM. If i have android as well as ios app do i need to do `Rpush::Gcm::Notification.new` with `auth_key` as the firebase's `server_key`? And then just this one app can be used to send notifications to android as well as ios?

Thanks in advance!

**Comment by benrugg** [comment]
Yes, to use FCM, you just use `Rpush::Gcm::Notification.new` like you said. For the `auth_key`, it's the API key that google provides (which I believe is the server key that you mentioned). And then the result is that you can send notifications to both iOS and Android.

**Comment by AkshayGoyal022** [comment]
Thanks for the response.

I have one more question though. As earlier, to send ios notifications we could only send to one device at a particular time but for android notification we could send in bulk. So now if we use FCM and pass all the device tokens in an array, will it work for ios? If yes, what happens in case of delivery error?

**Comment by benrugg** [comment]
Those are good questions... The way I used rpush, I sent android notifications through FCM and ios notifications through APNs. So I don't have firsthand experience sending everything through FCM. But I can tell you how rpush says it works:

1. in the case of a delivery error, the callbacks in the [Reflection API](https://github.com/rpush/rpush/wiki/Reflection-API) will be called. If only some tokens failed (ie. because of invalid device tokens), the ones that failed will all be handled individually. If the entire delivery failed (ie. because of a connection error), it will be retried automatically by rpush.

2. I _think_ you can make a single call with an array of registration id's for FCM that will go to both ios and android users. (someone else should definitely confirm this)

**Comment by wyde19** [comment]
@benrugg AFAIK server_key is the legacy method for FCM authporization. Now they use short-lived OAuth bearer keys.
