### ISSUE TITLE
APNSp8 dispatcher occasionally hangs

### ISSUE THREAD

**Issue by jhottenstein** [rpush/rpush#477]
We are using the apnsp8 adapter to send a large amount of push notifications and we will occasionally (~6 times/day) get a batch that will error out after 7200 seconds (when the remote connection is closed).

I believe this is the same problem reported in #354

I think setting a timeout around client.join (or inside client.join is the appropriate solution).

**Comment by aried3r** [comment]
Hey! Thanks for all the opened issues and especially for the PRs. I was wondering, do you want to be a contributer of rpush so you can merge PRs yourself? 
Don't worry, there's no responsibility to maintain anything, but since I'm not even using APNS, I can't really be of much help reviewing the PRs.

**Comment by jhottenstein** [comment]
@aried3r I would be happy to help.  Thank you.

I ended up adding an idle timeout to the socket loop in [net/http2](https://github.com/splitwise/net-http2/tree/add-idle-timeout).  This worked but the timeout is orphaning notifications in our db (we use redis) so I don't want to push it as a solution for this issue yet.

It's unclear if we should resend them (and risk double delivery) or ignore them (and risk no delivery).

I would like to add some logging and see if this is a library issue with net-http2 (the on close event is not getting triggered) or if it is an apns issue (the end_stream frame is never being sent).

**Comment by aried3r** [comment]
Hey @jhottenstein, I just wanted to follow up on this. I think you've seen that I've invited you to be a collaborator of this repo. :)

Did you get a stable working version running with a timeout in net-http2?

**Comment by rofreg** [comment]
@aried3r Jess is off on vacation right now, but I can chime in :)

Unfortunately we haven't followed up further on this issue yet – we set aside our APNS p8 migration for the time being to focus on other work. As Jess noted, [we deployed an implementation with net-http2 timeouts](https://github.com/splitwise/rpush/tree/add-timeout-to-apns-p8) based on a [custom fork of net-http2](https://github.com/ostinelli/net-http2/compare/master...splitwise:master), which solved one problem but caused another. Each time the timeout triggered, a notification would become orphaned in our data store. It was unclear whether the orphaned notifications had been delivered or not before they became orphaned.

When we return to this problem, our next step will be to add more logging to help narrow down where the problem lies within net-http2/apns/rpush. Definitely more investigation to be done – for now, we've continued to use the original APNS adapter.

**Comment by andresbravog** [comment]
We are suffering the same issue, after some days the daemon gets stuck on APNSp8 notifications taking up to 3s per notification.

Any progress on this?

**Comment by benlangfeld** [comment]
I'm also experiencing this problem. It looks like https://github.com/splitwise/rpush/pull/7 probably fixes this, though could also mark the batch for retry.

It's an urgent issue, since during this failure rpush continues pulling notifications out of the pending queue in redis and queueing them in memory; since it gets stuck and we have to send it SIGKILL, those notifications queued in memory will forever sit in redis in a state such that the new rpush instance that replaces the hung one won't pick them up, and they'll thus never be sent. Keeping this set small by dropping only the batch which we got stuck on (and unblocking to attempt to send the next batch) is an improvement to delivery reliability, but we can also re-queue the potentially-failed notifications; this may result in that small batch being delivered a second time, but that's still an improvement.

I have resources at my disposal and significant urgency to get this fix into a release of rpush if you need help @jhottenstein @aried3r

**Comment by rofreg** [comment]
Hey @benlangfeld, so sorry you're having the same problem! Unfortunately @jhottenstein and I abandoned this issue shortly after our initial research above, and instead we switched to FCM to deliver both iOS and Android notifications. I still think fixing APNSp8 support would be a really valuable contribution to rpush, but it's not something we're actively working on anymore.
