### ISSUE TITLE
Android badges does't work

### ISSUE THREAD

**Issue by hwth** [rpush/rpush#481]
I added the badge number to the notification body, but the badge didn't display.
It works normally on iOS devices.

**Comment by aried3r** [comment]
Hey! That's because Android (AOSP) doesn't have support for badges. You can also see here in [Table 2.b (Android)](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) that there is indeed no field for a badge.

However Android 8.0 introduced [Notification Badges](https://developer.android.com/training/notify-user/badges) or "dots", but they come automatically without any additional support via notification payloads.

What you might be thinking of are the badges some OEMs add themselves, for example Samsung does this. There are libraries that try to help you do this, for example [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger).

As this is not a problem with Rpush I'm closing this and hope you are successful in displaying badges in your app, cheers!

**Comment by hwth** [comment]
Yeah, it's good to know. Thank you so much (y)
