### ISSUE TITLE
apnsp8 still uses apns feedback

### ISSUE THREAD

**Issue by jose-airspace** [rpush/rpush#604]
I am getting the exact issue described in the following thread: https://developer.apple.com/forums/thread/86415 
When I switched to apnsp8 I do not get immediate errors but if I call for feedback, I see the errors. I'm thinking we need to include `apnsp8` in `next unless app.service_name == 'apns'` in `rpush-5.4.0/lib/rpush/apns_feedback.rb:9`?

**Comment by paulccarey** [comment]
I've been looking into this as we've not received any APNS feedback since we switched over to APNS2 and since APNSP8

From what I'm reading it looks like the feedback service has been discontinued and you should look for errors coming back when the notification fails that inform you the recipient is unregistered.

[If the token is unregistered you will get error code 410](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/handling_notification_responses_from_apns)

You can use the `Reflect` API with something like...
```ruby
Rpush.reflect do |on|
  on.notification_failed do |rpush_notification|
      your_unregister_call if rpush_notification.error_code == 410 
  end
end
```
